-- | Events generated by the DOM
module Data.VDOM.Internal.Pipes.DOM where

import qualified Data.VDOM.Internal.FFI             as FFI
import           Data.VDOM.Internal.Pipes.WebWorker (Input)
import qualified Data.VDOM.Internal.Pipes.WebWorker as W
import           Data.VDOM.Internal.Types           (ElementId (..), Event (..),
                                                     fromClickData)
import           GHCJS.Prim                         (JSVal)

onClick :: JSVal -> IO (Input (Event a ElementId))
onClick target = W.createInput (f' $ FFI.setOnClick target)  W.unbounded where
  f' cb cb' = cb (\cd -> cb' (fromClickData cd))

